StoreManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("storeapp.urls")),
]

storeapp/urls.py
from django.urls import path

from . import views

app_name = "storeapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.sign_up, name='signup'),
    path('signup/<str:person>', views.signup2, name='signup2'),
    path('login/', views.login_in, name='login'),
    path('logout/', views.logout_out, name='logout'),
    path('create-task/', views.create_task, name='createtask'),
    path('assign-task/', views.assign_task, name='assigntask'),
    path('task/<int:task_id>/assign/', views.accept_task, name='accept-task'),
    path('change-task-status/', views.change_task_status, name='change-task-status'),
    path('change-task-status/<int:task_id>/', views.change_status, name='change-status'),
]

storeapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class StoreManager(models.Model):

    store_name = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=25)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class DeliveryPerson(models.Model):
    name = models.CharField(max_length=25)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Task(models.Model):
    status_choices = (
        ('new', 'new'),
        ('accepted', "accepted"),
        ('completed', 'completed'),
        ('declined', 'declined')
    )

    priority_choices = (
        ('high', 'high'),
        ('medium', 'medium'),
        ('low', 'low'),
    )

    title = models.CharField(max_length=25)
    status = models.CharField(max_length=10, choices=status_choices)
    priority = models.CharField(max_length=10, choices=priority_choices)
    created_by = models.CharField(max_length=50)
    store_manager = models.ForeignKey(StoreManager, on_delete=models.CASCADE)
    delivery_person = models.ForeignKey(DeliveryPerson, on_delete=models.DO_NOTHING, null=True, blank=True)

    def __str__(self):
        return self.title

storeapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import StoreManager, Task, DeliveryPerson


class StoreManagerForm(forms.ModelForm):
    class Meta:
        model = StoreManager
        fields = ['name','store_name']


class DeliveryPersonForm(forms.ModelForm):
    class Meta:
        model = DeliveryPerson
        fields = ['name', ]


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'priority']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

storeapp/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.models import User

from .models import Task, StoreManager, DeliveryPerson
from .forms import StoreManagerForm, TaskForm, DeliveryPersonForm, UserForm

# Create your views here.


def index(request):
    return render(request, 'storeapp/index.html')


def sign_up(request):
    if request.method == 'POST':
        person = request.POST['person']
        return HttpResponseRedirect(reverse('storeapp:signup2', args=(person,)))
    return render(request, 'storeapp/signup.html')


# def signup2(request, person):
#     # print(person)
#
#     if request.method == "POST":
#         form = eval(person + 'Form()')
#         print(form['name'])
#         pass
#         # person = eval(person+'Form(request.POST)')
#     #     print(person)
#     form = eval(person + 'Form()')
#
#     return render(request, 'storeapp/signup2.html', {'form': form})


def signup2(request, person):
    userform = UserForm()

    if person == 'StoreManager':
        if request.method == 'POST':
            form = StoreManagerForm(request.POST)
            user = User.objects.create(
                username=request.POST['username'],
                password=request.POST['password'],
                email=request.POST['email'],
            )
            profile = form.save(commit=False)
            profile.user = user
            profile.save()
            return HttpResponseRedirect(reverse('storeapp:index'))

        form = StoreManagerForm()
        return render(request, 'storeapp/signup2.html', {'form': form, 'userform': userform})
    elif person == 'DeliveryPerson':
        if request.method == 'POST':
            form = DeliveryPersonForm(request.POST)
            user = User.objects.create(
                username=request.POST['username'],
                password=request.POST['password'],
                email=request.POST['email'],
            )
            profile = form.save(commit=False)
            profile.user = user
            profile.save()
            return HttpResponseRedirect(reverse('storeapp:index'))

        form = DeliveryPersonForm()
        return render(request, 'storeapp/signup2.html', {'form': form, 'userform': userform})
    else:
        return Http404


def login_in(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            try:
                manager = get_object_or_404(StoreManager, user=user)
                return HttpResponseRedirect(reverse('storeapp:createtask'))
            except:
                pass
            try:
                person = get_object_or_404(DeliveryPerson, user=user)
                return HttpResponseRedirect(reverse('storeapp:assigntask'))
            except:
                pass


        else:
            return render(request, 'storeapp/login.html')
    return render(request, 'storeapp/login.html')


def logout_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('storeapp:login'))


@login_required(login_url='login')
def create_task(request):
    user = request.user
    try:
        manager = get_object_or_404(StoreManager, user=user)
        if request.method == "POST":
            import pdb;pdb.set_trace()
            form = TaskForm(request.POST)
            task = form.save(commit=False)
            task.status = 'new'
            task.store_manager = manager
            task.created_by = manager.name
            task.save()
            return HttpResponseRedirect(reverse('storeapp:index'))
        form = TaskForm()
        return render(request, 'storeapp/create-task.html', {'form': form})
    except:
        return HttpResponse('failed')


@login_required(login_url='login')
def assign_task(request):
    user = request.user
    try:
        person = get_object_or_404(DeliveryPerson, user=user)
        task = Task.objects.filter(status='new')
        old_task = Task.objects.exclude(status='new')
        return render(request, 'storeapp/assign-task.html', {'task_list': task, "old_task": old_task})
    except:
        return HttpResponse('failed')


@login_required(login_url='login')
def accept_task(request, task_id):
    # import pdb; pdb.set_trace()
    task = get_object_or_404(Task, id=task_id)
    user = request.user
    form = TaskForm(instance=task)

    if task.status == 'new':
        try:
            person = get_object_or_404(DeliveryPerson, user=user)
            if person.count < 4:
                person.count += 1
                person.save()
                var = form.save(commit=False)
                var.status = 'accepted'
                var.delivery_person = person
                var.save()
                return HttpResponse(task, person)
            return HttpResponseRedirect(reverse('storeapp:assigntask'))
        except:
            return Http404
    return HttpResponse('failed')


@login_required(login_url='login')
def change_task_status(request):
    user = request.user
    try:
        person = get_object_or_404(DeliveryPerson, user=user)
        task_list = person.task_set.all()
        if request.method == "POST":
            return HttpResponse('Success')
        return render(request, "storeapp/change-task-status.html", {'task_list': task_list})
    except:
        return HttpResponse('Failed')


@login_required(login_url='login')
def change_status(request, task_id):
    user = request.user
    try:
        person = get_object_or_404(DeliveryPerson, user=user)
        task = get_object_or_404(Task, id=task_id)
        if request.method == "POST":

            status = request.POST['status']
            obj = Task.objects.filter(status='accepted').values('status').annotate(count=Count('id'))
            person.count = obj[0]['count']
            person.save()
            task.status = status
            task.save()
            return HttpResponseRedirect(reverse('storeapp:change-task-status'))
        return render(request, "storeapp/change-status.html", {'task': task})
    except:
        return HttpResponse('Failed')

storeapp/templates/storeapp/assign-task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TASK ASSIGN</title>
</head>
<body>
{% if old_task %}
<h1>Assigned tasks</h1>
{% for task in old_task %}
{{task.title}}--
<input type="text" value="{{task.status}}" name="title" readonly>
{{task.delivery_person}}
<br>
{% endfor %}
{% endif %}
<h1>New Tasks</h1>
{% for task in task_list %}
{{task.title}}--
<input type="text" value="{{task.status}}" name="title" readonly>
- - - <a href="/api/task/{{task.id}}/assign/">Assign</a>
<br>
{% endfor %}
</body>
</html>

storeapp/templates/storeapp/change-status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change task status</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
{{task}}-
<select name="status">
    <option value="accepted" selected>accepted</option>
    <option value="completed">completed</option>
    <option value="declined">declined</option>
</select>
    <button type="submit">Done</button><br>
</form>
</body>
</html>

storeapp/templates/storeapp/change-task-status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Status change</title>
</head>
<body>
{% for task in task_list %}
{{task.title}}--{{task.status}}
<a href="/api/change-task-status/{{task.id}}/">Change status</a><br><br>
{% endfor %}
</body>
</html>

storeapp/templates/storeapp/create-task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TASK CREATION</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
       {% csrf_token %}
  {% for field in form %}
    {{ field.label_tag }} {{ field }}<br>
  {% endfor %}
    <input type="submit" value="create">
</form>
</body>
</html>

storeapp/templates/storeapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index Page</title>
</head>
<body>
<a href="{% url 'storeapp:login' %}">LOGIN</a><br>
<a href="{% url 'storeapp:signup' %}">SIGN UP</a><br>
</body>
</html>

storeapp/templates/storeapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN PAGE</title>
</head>
<body>

<form action="." method="post" >
    {% csrf_token %}
    User Name : <input type="text" name="username"><br>
    Password : <input type="text" name="password"><br>
    <button type="submit">Login</button><br>
</form>
<a href = "{% url 'storeapp:signup' %}">Registration</a>
</body>
</html>

storeapp/templates/storeapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
<select name="person" id="person">
    <option value="StoreManager">StoreManager</option>
    <option value="DeliveryPerson">DeliveryPerson</option>
</select>
    <input type="submit" value="create">
</form>
</body>
</html>

storeapp/templates/storeapp/signup2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SignUp</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
   {% csrf_token %}
    username:<input type="text" name="username"><br>
    password:<input type="password" name="password"><br>
    email:<input type="email" name="email"><br>
  {% for field in form %}
    {{ field.label_tag }} {{ field }}<br>
  {% endfor %}
    <input type="submit" value='create'>
</form>
</body>
</html>